; NOTE: Assertions have been autogenerated by test/update_tpde_llc_test_checks.py UTC_ARGS: --version 5
; SPDX-License-Identifier: LicenseRef-Proprietary

; RUN: tpde-llc --target=x86_64 %s | %objdump | FileCheck %s -check-prefixes=X64

define void @inlineasm() {
; X64-LABEL: <inlineasm>:
; X64:         push rbp
; X64-NEXT:    mov rbp, rsp
; X64-NEXT:    nop word ptr [rax + rax]
; X64-NEXT:    sub rsp, 0x30
; X64-NEXT:    add rsp, 0x30
; X64-NEXT:    pop rbp
; X64-NEXT:    ret
  call void asm "", "~{dirflag},~{fpsr},~{flags}"()
  call void asm sideeffect "", "~{dirflag},~{fpsr},~{flags}"()
  call void asm unwind "", "~{dirflag},~{fpsr},~{flags}"()
  call void asm sideeffect "", "~{memory},~{dirflag},~{fpsr},~{flags}"()
  call void asm unwind "", "~{memory},~{dirflag},~{fpsr},~{flags}"()
  ret void
}
