// SPDX-FileCopyrightText: 2024 Tobias Kamm <tobias.kamm@tum.de>
// SPDX-FileCopyrightText: 2024 Tobias Schwarz <tobias.schwarz@tum.de>
//
// SPDX-License-Identifier: LicenseRef-Proprietary
#pragma once

// TODO(ts): I'd really like to keep these as normal headers in the source tree
// and generate this header
// TODO(ts): then also work with placeholders like
// -- DECLS_HERE --
// or
// -- IMPL_HERE --

namespace tpde_encgen::x64 {
static constexpr inline char ENCODER_TEMPLATE_BEGIN[] =
    R"(// SPDX-FileCopyrightText: 2024 Tobias Schwarz <tobias.schwarz@tum.de>
// SPDX-FileCopyrightText: 2024 Tobias Kamm <tobias.kamm@tum.de>
//
// SPDX-License-Identifier: LicenseRef-Proprietary AND CC0-1.0

// NOTE: This file is autogenerated by tpde-encodegen. Please DO NOT edit this file
// as all changes will be overwritten once the file is generated again.
// NOTE: Some parts of this file are subject to the default license of TPDE
// and only the autogenerated code falls under the CC0-1.0 license

// SPDX-SnippetBegin
// SPDX-License-Identifier: LicenseRef-Proprietary
#pragma once

#include <optional>
#include <variant>

#include "tpde/base.hpp"
#include "tpde/x64/CompilerX64.hpp"

// Helper macros for assembling in the compiler
#if defined(ASMD)
    #error Got definition for ASM macros from somewhere else. Maybe you included compilers for multiple architectures?
#endif

#define ASMD(...) ASMC(this->derived(), __VA_ARGS__)

namespace tpde_encodegen {

using namespace tpde;

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          typename BaseTy,
          typename Config>
struct EncodeCompiler {
    using CompilerX64  = tpde::x64::CompilerX64<Adaptor, Derived, BaseTy, Config>;
    using ScratchReg   = typename CompilerX64::ScratchReg;
    using AsmReg       = typename CompilerX64::AsmReg;
    using ValuePartRef = typename CompilerX64::ValuePartRef;
    using GenericValuePart = typename CompilerX64::GenericValuePart;
    using Assembler    = typename CompilerX64::Assembler;
    using Label        = typename Assembler::Label;
    using ValLocalIdx  = typename CompilerX64::ValLocalIdx;
    using SymRef       = typename Assembler::SymRef;

    [[nodiscard]] static std::optional<i32> encodeable_as_imm32_sext(GenericValuePart &gv) noexcept;
    [[nodiscard]] static std::optional<FeMem> encodeable_as_mem(GenericValuePart &gv, unsigned align) noexcept;
    [[nodiscard]] static std::optional<FeMem> encodeable_with(GenericValuePart &gv, FeMem other) noexcept;
    void          try_salvage_or_materialize(GenericValuePart &gv,
                                             ScratchReg     &dst_scratch,
                                             u8              bank,
                                             u32             size) noexcept;

    CompilerX64 *derived() noexcept {
        return static_cast<CompilerX64 *>(static_cast<Derived *>(this));
    }

    const CompilerX64 *derived() const noexcept {
        return static_cast<const CompilerX64 *>(
            static_cast<const Derived *>(this));
    }

    static bool reg_needs_avx512(AsmReg reg) noexcept {
        if (reg.id() > AsmReg::XMM15) {
            return true;
        }
        return false;
    }

    [[nodiscard]] bool has_avx() const noexcept {
        return derived()->has_cpu_feats(CompilerX64::CPU_AVX);
    }

    [[nodiscard]] static bool disp_add_encodeable(int32_t disp,
                                                  int32_t add) noexcept {
        const auto tmp = static_cast<int64_t>(disp) + add;
        return (static_cast<int64_t>(static_cast<int32_t>(tmp)) == tmp);
    }

    struct FixedRegBackup {
        ScratchReg  scratch;
        ValLocalIdx local_idx;
        u32         part;
        u32         lock_count;
    };

    void scratch_alloc_specific(AsmReg                              reg,
                                ScratchReg                         &scratch,
                                std::initializer_list<GenericValuePart *> operands,
                                FixedRegBackup &backup_reg) noexcept;

    void scratch_check_fixed_backup(ScratchReg     &scratch,
                                    FixedRegBackup &backup_reg,
                                    bool            is_ret_reg) noexcept;

    void reset() noexcept {
        symbols.fill({});
    }

// SPDX-SnippetEnd
// SPDX-SnippetBegin
// SPDX-License-Identifier: CC0-1.0
// clang-format off
)";

static constexpr inline char ENCODER_TEMPLATE_END[] = R"(
};
// SPDX-SnippetEnd
)";

static constexpr inline char ENCODER_IMPL_TEMPLATE_BEGIN[] = R"(

// SPDX-SnippetBegin
// SPDX-License-Identifier: LicenseRef-Proprietary
// clang-format on
template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
std::optional<i32> EncodeCompiler<Adaptor, Derived, BaseTy, Config>::
    encodeable_as_imm32_sext(GenericValuePart &gv) noexcept {
    if (!gv.is_imm()) {
        return std::nullopt;
    }

    const u64 imm = gv.imm64();
    if (gv.imm_size() <= 4 || static_cast<i64>(static_cast<i32>(imm)) == static_cast<i64>(imm)) {
        // always encodeable
        return static_cast<i32>(imm);
    }

    return std::nullopt;
}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
std::optional<FeMem> EncodeCompiler<Adaptor, Derived, BaseTy, Config>::
    encodeable_as_mem(GenericValuePart &gv, unsigned align) noexcept {
    if (!std::holds_alternative<ValuePartRef>(gv.state)) {
        return std::nullopt;
    }
    const ValuePartRef &vpr = std::get<ValuePartRef>(gv.state);

    if (!vpr.has_assignment()) {
        return std::nullopt;
    }

    const auto ap = vpr.assignment();
    if (ap.register_valid() || ap.variable_ref())
        return std::nullopt;
    if (ap.frame_off() & (align - 1))
        return std::nullopt;
    return FE_MEM(FE_BP, 0, FE_NOREG, -static_cast<i32>(ap.frame_off()));
}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
std::optional<FeMem> EncodeCompiler<Adaptor, Derived, BaseTy, Config>::
    encodeable_with(GenericValuePart &gv, FeMem other) noexcept {
    const auto disp_encodeable = [](u64 a, u64 b) -> std::optional<i32> {
        auto sum = static_cast<i32>(a + b);
        if (static_cast<i64>(sum) == static_cast<i64>(a + b))
            return sum;
        return std::nullopt;
    };
    const auto is_noreg = [](FeRegGP gp) {
        return gp.idx == FE_NOREG.idx;
    };

    if (gv.is_imm()) {
        if (auto disp = disp_encodeable(gv.imm64(), other.off))
            return FE_MEM(other.base, other.scale, other.idx, *disp);
        return std::nullopt;
    }
    if (const auto *reg = std::get_if<ScratchReg>(&gv.state)) {
        if (is_noreg(other.base))
            return FE_MEM(reg->cur_reg(), other.scale, other.idx, other.off);
        if (is_noreg(other.idx))
            return FE_MEM(other.base, 1, reg->cur_reg(), other.off);
        return std::nullopt;
    }
    if (const auto *expr = std::get_if<typename GenericValuePart::Expr>(&gv.state)) {
        // TODO: check completeness
        auto disp = disp_encodeable(expr->disp, other.off);
        if (!disp)
            return std::nullopt;
        if (!expr->has_index()) {
            if (!expr->has_base())
                return FE_MEM(other.base, other.scale, other.idx, *disp);
            if (is_noreg(other.base))
                return FE_MEM(expr->base_reg(), other.scale, other.idx, *disp);
            if (is_noreg(other.idx))
                return FE_MEM(other.base, 1, expr->base_reg(), *disp);
            return std::nullopt;
        }
        if (expr->scale != 1 && expr->scale != 2 && expr->scale != 4 && expr->scale != 8)
            return std::nullopt;
        auto scale = static_cast<u8>(expr->scale);
        if (!is_noreg(other.idx))
            return std::nullopt;
        if (!expr->has_base())
            return FE_MEM(other.base, scale, expr->index_reg(), *disp);
        if (is_noreg(other.base) && expr->has_base())
            return FE_MEM(expr->base_reg(), scale, expr->index_reg(), *disp);
        return std::nullopt;
    }
    // TODO: ValuePartRef?
    return std::nullopt;
}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
void EncodeCompiler<Adaptor, Derived, BaseTy, Config>::
    try_salvage_or_materialize(GenericValuePart &gv,
                               ScratchReg     &dst_scratch,
                               u8              bank,
                               u32             size) noexcept {
    AsmReg reg = derived()->gval_as_reg_reuse(gv, dst_scratch);
    if (!dst_scratch.has_reg()) {
        dst_scratch.alloc(bank);
    }
    if (dst_scratch.cur_reg() != reg) {
        derived()->mov(dst_scratch.cur_reg(), reg, size);
    }
}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
void EncodeCompiler<Adaptor, Derived, BaseTy, Config>::scratch_alloc_specific(
    AsmReg                              reg,
    ScratchReg                         &scratch,
    std::initializer_list<GenericValuePart *> operands,
    FixedRegBackup                     &backup_reg) noexcept {
    if (!derived()->register_file.is_fixed(reg)) [[likely]] {
        scratch.alloc_specific(reg);
        return;
    }

    const auto bank = derived()->register_file.reg_bank(reg);
    if (bank != 0) {
        // TODO(ts): need to know the size
        TPDE_FATAL("fixed non-gp regs not supported");
    }

    const auto alloc_backup = [this, &backup_reg, &scratch, reg, bank]() {
        const auto bak_reg    = backup_reg.scratch.alloc(bank);
        auto      &reg_file   = derived()->register_file;
        auto      &assignment = reg_file.assignments[reg.id()];
        backup_reg.local_idx  = assignment.local_idx;
        backup_reg.part       = assignment.part;
        backup_reg.lock_count = reg_file.lock_counts[reg.id()];

        assignment.local_idx  = CompilerX64::INVALID_VAL_LOCAL_IDX;
        assignment.part       = 0;
        reg_file.lock_counts[reg.id()] = 0;

        assert(!scratch.has_reg());
        scratch.force_set_reg(reg);

        ASMD(MOV64rr, bak_reg, reg);
    };

    // check if one of the operands holds the fixed register
    for (auto *op_ptr : operands) {
        auto &op = op_ptr->state;
        if (std::holds_alternative<ScratchReg>(op)) {
            auto &op_scratch = std::get<ScratchReg>(op);
            if (op_scratch.cur_reg() == reg) {
                scratch = std::move(op_scratch);
                op_scratch.alloc(bank);
                ASMD(MOV64rr, op_scratch.cur_reg(), reg);
                return;
            }
            continue;
        }

        if (std::holds_alternative<ValuePartRef>(op)) {
            auto &op_ref = std::get<ValuePartRef>(op);
            if (op_ref.has_assignment()) {
                assert(!op_ref.has_reg());
                const auto ap = op_ref.assignment();
                if (ap.register_valid()) {
                    assert(AsmReg{ap.full_reg_id()} != reg);
                }
            } else if (op_ref.state.c.reg == reg) {
                assert(0 && "not implemented");
            }
            continue;
        }

        if (std::holds_alternative<typename GenericValuePart::Expr>(op)) {
            auto &expr = std::get<typename GenericValuePart::Expr>(op);
            if (expr.base_reg() == reg) {
                if (std::holds_alternative<ScratchReg>(expr.base)) {
                    auto &op_scratch = std::get<ScratchReg>(expr.base);
                    scratch          = std::move(op_scratch);
                    op_scratch.alloc(bank);
                    ASMD(MOV64rr, op_scratch.cur_reg(), reg);
                } else {
                    alloc_backup();
                    expr.base = backup_reg.scratch.cur_reg();
                }
                return;
            }
            if (expr.scale != 0 && expr.index_reg() == reg) {
                if (std::holds_alternative<ScratchReg>(expr.index)) {
                    auto &op_scratch = std::get<ScratchReg>(expr.index);
                    scratch          = std::move(op_scratch);
                    op_scratch.alloc(bank);
                    ASMD(MOV64rr, op_scratch.cur_reg(), reg);
                } else {
                    alloc_backup();
                    expr.index = backup_reg.scratch.cur_reg();
                }
                return;
            }
            continue;
        }
    }

    // otherwise temporarily store it somewhere else
    alloc_backup();
    return;
}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
void EncodeCompiler<Adaptor, Derived, BaseTy, Config>::
    scratch_check_fixed_backup(ScratchReg     &scratch,
                               FixedRegBackup &backup_reg,
                               const bool      is_ret_reg) noexcept {
    if (!backup_reg.scratch.has_reg()) [[likely]] {
        return;
    }

    assert(scratch.has_reg());
    auto &reg_file        = derived()->register_file;
    auto &assignment      = reg_file.assignments[scratch.cur_reg().id()];
    assignment.local_idx  = backup_reg.local_idx;
    assignment.part       = backup_reg.part;
    reg_file.lock_counts[scratch.cur_reg().id()] = backup_reg.lock_count;

    assert(reg_file.reg_bank(scratch.cur_reg()) == 0);
    if (is_ret_reg) {
        // TODO(ts): allocate another scratch? Though at this point the scratch
        // regs have not been released yet so we might need to spill...

        // need to switch around backup and reg so it can be returned as a
        // ScratchReg
        ASMD(XCHG64rr, scratch.cur_reg(), backup_reg.scratch.cur_reg());
        scratch.force_set_reg(backup_reg.scratch.cur_reg());
        backup_reg.scratch.force_set_reg(AsmReg::make_invalid());
    } else {
        ASMD(MOV64rr, scratch.cur_reg(), backup_reg.scratch.cur_reg());

        scratch.force_set_reg(AsmReg::make_invalid());
        backup_reg.scratch.reset();
    }
}

// clang-format off
// SPDX-SnippetEnd
// SPDX-SnippetBegin
// SPDX-License-Identifier: CC0-1.0
)";


static constexpr inline char ENCODER_IMPL_TEMPLATE_END[] = R"(
} // namespace tpde_encodegen

#undef ASMD
// SPDX-SnippetEnd
)";
} // namespace tpde_encgen::x64
