; NOTE: Assertions have been autogenerated by utils/update_tpde_llvm_test_checks.py UTC_ARGS: --tool tpde_llvm --default-march x86-64-v2 --filter-out "int3" --version 5
; SPDX-FileCopyrightText: 2024 Tobias Schwarz <tobias.schwarz@tum.de>
;
; SPDX-License-Identifier: LicenseRef-Proprietary

; RUN: tpde_llvm %s | llvm-objdump -d -r --no-show-raw-insn --symbolize-operands --no-addresses --x86-asm-syntax=intel --section=.text --section=.rodata - | FileCheck %s -check-prefixes=X64,CHECK --enable-var-scope --dump-input always


%struct.i8_i32 = type { i8, i32 }
%struct.ptr_i32 = type { ptr, i32 }
%struct.f32_ptr = type { float, ptr }
%struct.i128_i1 = type { i128, i1 }

define i8 @extract_i8_i32_0(ptr %0) {
; X64-LABEL: extract_i8_i32_0>:
; X64:    push rbp
; X64:    mov rbp, rsp
; X64:    nop word ptr [rax + rax]
; X64:    sub rsp, 0x20
; X64:    movzx eax, byte ptr [rdi]
; X64:    mov ecx, dword ptr [rdi + 0x4]
; X64:    add rsp, 0x20
; X64:    pop rbp
; X64:    ret
; X64:    add byte ptr [rax], al
; X64:    add byte ptr [rax], al
entry:
  %1 = load %struct.i8_i32, ptr %0
  %2 = extractvalue %struct.i8_i32 %1, 0
  ret i8 %2
}

define i32 @extract_i8_i32_1(ptr %0) {
; X64-LABEL: extract_i8_i32_1>:
; X64:    push rbp
; X64:    mov rbp, rsp
; X64:    nop word ptr [rax + rax]
; X64:    sub rsp, 0x20
; X64:    movzx eax, byte ptr [rdi]
; X64:    mov ecx, dword ptr [rdi + 0x4]
; X64:    mov eax, ecx
; X64:    add rsp, 0x20
; X64:    pop rbp
; X64:    ret
; X64:    add byte ptr [rax], al
entry:
  %1 = load %struct.i8_i32, ptr %0
  %2 = extractvalue %struct.i8_i32 %1, 1
  ret i32 %2
}

define i8 @extract_i8_i32_0_no_salvage(ptr %0) {
; X64-LABEL: extract_i8_i32_0_no_salvage>:
; X64:    push rbp
; X64:    mov rbp, rsp
; X64:    nop word ptr [rax + rax]
; X64:    sub rsp, 0x20
; X64:    movzx eax, byte ptr [rdi]
; X64:    mov ecx, dword ptr [rdi + 0x4]
; X64:    mov edx, eax
; X64:    mov byte ptr [rdi], al
; X64:    mov dword ptr [rdi + 0x4], ecx
; X64:    mov eax, edx
; X64:    add rsp, 0x20
; X64:    pop rbp
; X64:    ret
; X64:     ...
; X64:    add byte ptr [rax], al
; X64:    add byte ptr [rbp + 0x48], dl
entry:
  %1 = load %struct.i8_i32, ptr %0
  %2 = extractvalue %struct.i8_i32 %1, 0
  store %struct.i8_i32 %1, ptr %0
  ret i8 %2
}

define i32 @extract_i8_i32_1_no_salvage(ptr %0) {
; X64-LABEL: extract_i8_i32_1_no_salvage>:
; X64:    push rbp
; X64:    mov rbp, rsp
; X64:    nop word ptr [rax + rax]
; X64:    sub rsp, 0x20
; X64:    movzx eax, byte ptr [rdi]
; X64:    mov ecx, dword ptr [rdi + 0x4]
; X64:    mov edx, ecx
; X64:    mov byte ptr [rdi], al
; X64:    mov dword ptr [rdi + 0x4], ecx
; X64:    mov eax, edx
; X64:    add rsp, 0x20
; X64:    pop rbp
; X64:    ret
; X64:     ...
; X64:    add byte ptr [rax], al
; X64:    add byte ptr [rbp + 0x48], dl
entry:
  %1 = load %struct.i8_i32, ptr %0
  %2 = extractvalue %struct.i8_i32 %1, 1
  store %struct.i8_i32 %1, ptr %0
  ret i32 %2
}


define ptr @extract_ptr_i32_0(ptr %0) {
; X64-LABEL: extract_ptr_i32_0>:
; X64:    push rbp
; X64:    mov rbp, rsp
; X64:    nop word ptr [rax + rax]
; X64:    sub rsp, 0x20
; X64:    mov rax, qword ptr [rdi]
; X64:    mov ecx, dword ptr [rdi + 0x8]
; X64:    add rsp, 0x20
; X64:    pop rbp
; X64:    ret
; X64:    add byte ptr [rax], al
; X64:    add byte ptr [rax], al
entry:
  %1 = load %struct.ptr_i32, ptr %0
  %2 = extractvalue %struct.ptr_i32 %1, 0
  ret ptr %2
}

define i32 @extract_ptr_i32_1(ptr %0) {
; X64-LABEL: extract_ptr_i32_1>:
; X64:    push rbp
; X64:    mov rbp, rsp
; X64:    nop word ptr [rax + rax]
; X64:    sub rsp, 0x30
; X64:    mov rax, qword ptr [rdi]
; X64:    mov ecx, dword ptr [rdi + 0x8]
; X64:    mov eax, ecx
; X64:    add rsp, 0x30
; X64:    pop rbp
; X64:    ret
; X64:    add byte ptr [rax], al
entry:
  %1 = load %struct.ptr_i32, ptr %0
  %2 = extractvalue %struct.ptr_i32 %1, 1
  ret i32 %2
}

define ptr @extract_ptr_i32_0_no_salvage(ptr %0) {
; X64-LABEL: extract_ptr_i32_0_no_salvage>:
; X64:    push rbp
; X64:    mov rbp, rsp
; X64:    nop word ptr [rax + rax]
; X64:    sub rsp, 0x20
; X64:    mov rax, qword ptr [rdi]
; X64:    mov ecx, dword ptr [rdi + 0x8]
; X64:    mov rdx, rax
; X64:    mov qword ptr [rdi], rax
; X64:    mov dword ptr [rdi + 0x8], ecx
; X64:    mov rax, rdx
; X64:    add rsp, 0x20
; X64:    pop rbp
; X64:    ret
; X64:     ...
entry:
  %1 = load %struct.ptr_i32, ptr %0
  %2 = extractvalue %struct.ptr_i32 %1, 0
  store %struct.ptr_i32 %1, ptr %0
  ret ptr %2
}

define i32 @extract_ptr_i32_1_no_salvage(ptr %0) {
; X64-LABEL: extract_ptr_i32_1_no_salvage>:
; X64:    push rbp
; X64:    mov rbp, rsp
; X64:    nop word ptr [rax + rax]
; X64:    sub rsp, 0x30
; X64:    mov rax, qword ptr [rdi]
; X64:    mov ecx, dword ptr [rdi + 0x8]
; X64:    mov edx, ecx
; X64:    mov qword ptr [rdi], rax
; X64:    mov dword ptr [rdi + 0x8], ecx
; X64:    mov eax, edx
; X64:    add rsp, 0x30
; X64:    pop rbp
; X64:    ret
; X64:     ...
; X64:    add byte ptr [rax], al
entry:
  %1 = load %struct.ptr_i32, ptr %0
  %2 = extractvalue %struct.ptr_i32 %1, 1
  store %struct.ptr_i32 %1, ptr %0
  ret i32 %2
}


define float @extract_f32_ptr_0(ptr %0) {
; X64-LABEL: extract_f32_ptr_0>:
; X64:    push rbp
; X64:    mov rbp, rsp
; X64:    nop word ptr [rax + rax]
; X64:    sub rsp, 0x30
; X64:    movss xmm0, dword ptr [rdi]
; X64:    mov rax, qword ptr [rdi + 0x8]
; X64:    add rsp, 0x30
; X64:    pop rbp
; X64:    ret
; X64:    add byte ptr [rax], al
entry:
  %1 = load %struct.f32_ptr, ptr %0
  %2 = extractvalue %struct.f32_ptr %1, 0
  ret float %2
}

define ptr @extract_f32_ptr_1(ptr %0) {
; X64-LABEL: extract_f32_ptr_1>:
; X64:    push rbp
; X64:    mov rbp, rsp
; X64:    nop word ptr [rax + rax]
; X64:    sub rsp, 0x20
; X64:    movss xmm0, dword ptr [rdi]
; X64:    mov rax, qword ptr [rdi + 0x8]
; X64:    add rsp, 0x20
; X64:    pop rbp
; X64:    ret
; X64:    add byte ptr [rax], al
entry:
  %1 = load %struct.f32_ptr, ptr %0
  %2 = extractvalue %struct.f32_ptr %1, 1
  ret ptr %2
}

define float @extract_f32_ptr_0_no_salvage(ptr %0) {
; X64-LABEL: extract_f32_ptr_0_no_salvage>:
; X64:    push rbp
; X64:    mov rbp, rsp
; X64:    nop word ptr [rax + rax]
; X64:    sub rsp, 0x30
; X64:    movss xmm0, dword ptr [rdi]
; X64:    mov rax, qword ptr [rdi + 0x8]
; X64:    movupd xmm1, xmm0
; X64:    movss dword ptr [rdi], xmm0
; X64:    mov qword ptr [rdi + 0x8], rax
; X64:    movupd xmm0, xmm1
; X64:    add rsp, 0x30
; X64:    pop rbp
; X64:    ret
; X64:    add byte ptr [rax], al
entry:
  %1 = load %struct.f32_ptr, ptr %0
  %2 = extractvalue %struct.f32_ptr %1, 0
  store %struct.f32_ptr %1, ptr %0
  ret float %2
}

define ptr @extract_f32_ptr_1_no_salvage(ptr %0) {
; X64-LABEL: extract_f32_ptr_1_no_salvage>:
; X64:    push rbp
; X64:    mov rbp, rsp
; X64:    nop word ptr [rax + rax]
; X64:    sub rsp, 0x20
; X64:    movss xmm0, dword ptr [rdi]
; X64:    mov rax, qword ptr [rdi + 0x8]
; X64:    mov rcx, rax
; X64:    movss dword ptr [rdi], xmm0
; X64:    mov qword ptr [rdi + 0x8], rax
; X64:    mov rax, rcx
; X64:    add rsp, 0x20
; X64:    pop rbp
; X64:    ret
; X64:    add byte ptr [rax], al
; X64:    add byte ptr [rax], al
entry:
  %1 = load %struct.f32_ptr, ptr %0
  %2 = extractvalue %struct.f32_ptr %1, 1
  store %struct.f32_ptr %1, ptr %0
  ret ptr %2
}


define i128 @extract_i128_i1_0(ptr %0) {
; X64-LABEL: extract_i128_i1_0>:
; X64:    push rbp
; X64:    mov rbp, rsp
; X64:    nop word ptr [rax + rax]
; X64:    sub rsp, 0x40
; X64:    mov rax, qword ptr [rdi]
; X64:    mov rcx, qword ptr [rdi + 0x8]
; X64:    movzx edx, byte ptr [rdi + 0x10]
; X64:    mov rdx, rcx
; X64:    add rsp, 0x40
; X64:    pop rbp
; X64:    ret
; X64:     ...
entry:
  %1 = load %struct.i128_i1, ptr %0
  %2 = extractvalue %struct.i128_i1 %1, 0
  ret i128 %2
}

define i1 @extract_i128_i1_1(ptr %0) {
; X64-LABEL: extract_i128_i1_1>:
; X64:    push rbp
; X64:    mov rbp, rsp
; X64:    nop word ptr [rax + rax]
; X64:    sub rsp, 0x50
; X64:    mov rax, qword ptr [rdi]
; X64:    mov rcx, qword ptr [rdi + 0x8]
; X64:    movzx edx, byte ptr [rdi + 0x10]
; X64:    mov eax, edx
; X64:    add rsp, 0x50
; X64:    pop rbp
; X64:    ret
; X64:     ...
; X64:    add byte ptr [rbp + 0x48], dl
entry:
  %1 = load %struct.i128_i1, ptr %0
  %2 = extractvalue %struct.i128_i1 %1, 1
  ret i1 %2
}

define i128 @extract_i128_i1_0_no_salvage(ptr %0) {
; X64-LABEL: extract_i128_i1_0_no_salvage>:
; X64:    push rbp
; X64:    mov rbp, rsp
; X64:    nop word ptr [rax + rax]
; X64:    sub rsp, 0x40
; X64:    mov rax, qword ptr [rdi]
; X64:    mov rcx, qword ptr [rdi + 0x8]
; X64:    movzx edx, byte ptr [rdi + 0x10]
; X64:    mov rbx, rcx
; X64:    mov rsi, rax
; X64:    mov qword ptr [rdi + 0x8], rcx
; X64:    mov qword ptr [rdi], rax
; X64:    mov byte ptr [rdi + 0x10], dl
; X64:    mov rax, rsi
; X64:    mov rdx, rbx
; X64:    add rsp, 0x40
; X64:    pop rbp
; X64:    ret
; X64:     ...
; X64:    add byte ptr [rbp + 0x48], dl
entry:
  %1 = load %struct.i128_i1, ptr %0
  %2 = extractvalue %struct.i128_i1 %1, 0
  store %struct.i128_i1 %1, ptr %0
  ret i128 %2
}

define i1 @extract_i128_i1_1_no_salvage(ptr %0) {
; X64-LABEL: extract_i128_i1_1_no_salvage>:
; X64:    push rbp
; X64:    mov rbp, rsp
; X64:    nop word ptr [rax + rax]
; X64:    sub rsp, 0x50
; X64:    mov rax, qword ptr [rdi]
; X64:    mov rcx, qword ptr [rdi + 0x8]
; X64:    movzx edx, byte ptr [rdi + 0x10]
; X64:    mov ebx, edx
; X64:    mov qword ptr [rdi + 0x8], rcx
; X64:    mov qword ptr [rdi], rax
; X64:    mov byte ptr [rdi + 0x10], dl
; X64:    mov eax, ebx
; X64:    add rsp, 0x50
; X64:    pop rbp
; X64:    ret
; X64:     ...
; X64:    <unknown>
entry:
  %1 = load %struct.i128_i1, ptr %0
  %2 = extractvalue %struct.i128_i1 %1, 1
  store %struct.i128_i1 %1, ptr %0
  ret i1 %2
}

;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
