; NOTE: Assertions have been autogenerated by utils/update_tpde_llvm_test_checks.py UTC_ARGS: --tool tpde_llvm --default-march x86-64-v2 --filter-out "int3" --version 5
; SPDX-FileCopyrightText: 2024 Alexis Engelke <engelke@tum.de>
;
; SPDX-License-Identifier: LicenseRef-Proprietary

; RUN: tpde_llvm %s | llvm-objdump -d -r --no-show-raw-insn --symbolize-operands --no-addresses --x86-asm-syntax=intel - | FileCheck %s -check-prefixes=X64,CHECK --enable-var-scope --dump-input always
; RUN: tpde_llvm --target=aarch64 %s | llvm-objdump -d -r --no-show-raw-insn --symbolize-operands --no-addresses - | FileCheck %s -check-prefixes=ARM64,CHECK --enable-var-scope --dump-input always

define i1 @fcmp_f128_false(fp128 %0, fp128 %1) {
; X64-LABEL: fcmp_f128_false>:
; X64:    push rbp
; X64:    mov rbp, rsp
; X64:    nop word ptr [rax + rax]
; X64:    sub rsp, 0x60
; X64:    mov eax, 0x0
; X64:    add rsp, 0x60
; X64:    pop rbp
; X64:    ret
; X64:    add byte ptr [rax], al
; X64:    add byte ptr [rax], al
; X64:    add byte ptr [rbp + 0x48], dl
;
; ARM64-LABEL: fcmp_f128_false>:
; ARM64:    sub sp, sp, #0xd0
; ARM64:    stp x29, x30, [sp]
; ARM64:    mov x29, sp
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    mov w0, #0x0 // =0
; ARM64:    ldp x29, x30, [sp]
; ARM64:    add sp, sp, #0xd0
; ARM64:    ret
; ARM64:     ...
  %cmp = fcmp false fp128 %0, %1
  ret i1 %cmp
}

define i1 @fcmp_f128_true(fp128 %0, fp128 %1) {
; X64-LABEL: fcmp_f128_true>:
; X64:    push rbp
; X64:    mov rbp, rsp
; X64:    nop word ptr [rax + rax]
; X64:    sub rsp, 0x60
; X64:    mov eax, 0x1
; X64:    add rsp, 0x60
; X64:    pop rbp
; X64:    ret
; X64:    add byte ptr [rax], al
; X64:    add byte ptr [rax], al
; X64:    add byte ptr [rbp + 0x48], dl
;
; ARM64-LABEL: fcmp_f128_true>:
; ARM64:    sub sp, sp, #0xd0
; ARM64:    stp x29, x30, [sp]
; ARM64:    mov x29, sp
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    mov x0, #0x1 // =1
; ARM64:    ldp x29, x30, [sp]
; ARM64:    add sp, sp, #0xd0
; ARM64:    ret
; ARM64:     ...
  %cmp = fcmp true fp128 %0, %1
  ret i1 %cmp
}

define i1 @fcmp_f128_oge(fp128 %0, fp128 %1) {
; X64-LABEL: fcmp_f128_oge>:
; X64:    push rbp
; X64:    mov rbp, rsp
; X64:    nop word ptr [rax + rax]
; X64:    sub rsp, 0x60
; X64:  <L0>:
; X64:    call <L0>
; X64:     R_X86_64_PLT32 __getf2-0x4
; X64:    test rax, rax
; X64:    setge al
; X64:    movzx eax, al
; X64:    add rsp, 0x60
; X64:    pop rbp
; X64:    ret
; X64:     ...
;
; ARM64-LABEL: fcmp_f128_oge>:
; ARM64:    sub sp, sp, #0xd0
; ARM64:    stp x29, x30, [sp]
; ARM64:    mov x29, sp
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    bl 0x110 <fcmp_f128_oge+0x30>
; ARM64:     R_AARCH64_CALL26 __getf2
; ARM64:    cmp x0, #0x0
; ARM64:    cset w0, ge
; ARM64:    ldp x29, x30, [sp]
; ARM64:    add sp, sp, #0xd0
; ARM64:    ret
; ARM64:     ...
  %cmp = fcmp oge fp128 %0, %1
  ret i1 %cmp
}

define i1 @fcmp_f128_ord(fp128 %0, fp128 %1) {
; X64-LABEL: fcmp_f128_ord>:
; X64:    push rbp
; X64:    mov rbp, rsp
; X64:    nop word ptr [rax + rax]
; X64:    sub rsp, 0x60
; X64:  <L0>:
; X64:    call <L0>
; X64:     R_X86_64_PLT32 __unordtf2-0x4
; X64:    test rax, rax
; X64:    sete al
; X64:    movzx eax, al
; X64:    add rsp, 0x60
; X64:    pop rbp
; X64:    ret
; X64:     ...
;
; ARM64-LABEL: fcmp_f128_ord>:
; ARM64:    sub sp, sp, #0xd0
; ARM64:    stp x29, x30, [sp]
; ARM64:    mov x29, sp
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    bl 0x180 <fcmp_f128_ord+0x30>
; ARM64:     R_AARCH64_CALL26 __unordtf2
; ARM64:    cmp x0, #0x0
; ARM64:    cset w0, eq
; ARM64:    ldp x29, x30, [sp]
; ARM64:    add sp, sp, #0xd0
; ARM64:    ret
; ARM64:     ...
  %cmp = fcmp ord fp128 %0, %1
  ret i1 %cmp
}

define i1 @fcmp_f128_oeq(fp128 %0, fp128 %1) {
; X64-LABEL: fcmp_f128_oeq>:
; X64:    push rbp
; X64:    mov rbp, rsp
; X64:    nop word ptr [rax + rax]
; X64:    sub rsp, 0x60
; X64:  <L0>:
; X64:    call <L0>
; X64:     R_X86_64_PLT32 __eqtf2-0x4
; X64:    test rax, rax
; X64:    sete al
; X64:    movzx eax, al
; X64:    add rsp, 0x60
; X64:    pop rbp
; X64:    ret
; X64:     ...
;
; ARM64-LABEL: fcmp_f128_oeq>:
; ARM64:    sub sp, sp, #0xd0
; ARM64:    stp x29, x30, [sp]
; ARM64:    mov x29, sp
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    bl 0x1f0 <fcmp_f128_oeq+0x30>
; ARM64:     R_AARCH64_CALL26 __eqtf2
; ARM64:    cmp x0, #0x0
; ARM64:    cset w0, eq
; ARM64:    ldp x29, x30, [sp]
; ARM64:    add sp, sp, #0xd0
; ARM64:    ret
; ARM64:     ...
  %cmp = fcmp oeq fp128 %0, %1
  ret i1 %cmp
}

define i1 @fcmp_f128_ogt(fp128 %0, fp128 %1) {
; X64-LABEL: fcmp_f128_ogt>:
; X64:    push rbp
; X64:    mov rbp, rsp
; X64:    nop word ptr [rax + rax]
; X64:    sub rsp, 0x60
; X64:  <L0>:
; X64:    call <L0>
; X64:     R_X86_64_PLT32 __gttf2-0x4
; X64:    test rax, rax
; X64:    setg al
; X64:    movzx eax, al
; X64:    add rsp, 0x60
; X64:    pop rbp
; X64:    ret
; X64:     ...
;
; ARM64-LABEL: fcmp_f128_ogt>:
; ARM64:    sub sp, sp, #0xd0
; ARM64:    stp x29, x30, [sp]
; ARM64:    mov x29, sp
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    bl 0x260 <fcmp_f128_ogt+0x30>
; ARM64:     R_AARCH64_CALL26 __gttf2
; ARM64:    cmp x0, #0x0
; ARM64:    cset w0, gt
; ARM64:    ldp x29, x30, [sp]
; ARM64:    add sp, sp, #0xd0
; ARM64:    ret
; ARM64:     ...
  %cmp = fcmp ogt fp128 %0, %1
  ret i1 %cmp
}

define i1 @fcmp_f128_olt(fp128 %0, fp128 %1) {
; X64-LABEL: fcmp_f128_olt>:
; X64:    push rbp
; X64:    mov rbp, rsp
; X64:    nop word ptr [rax + rax]
; X64:    sub rsp, 0x60
; X64:  <L0>:
; X64:    call <L0>
; X64:     R_X86_64_PLT32 __lttf2-0x4
; X64:    test rax, rax
; X64:    setl al
; X64:    movzx eax, al
; X64:    add rsp, 0x60
; X64:    pop rbp
; X64:    ret
; X64:     ...
;
; ARM64-LABEL: fcmp_f128_olt>:
; ARM64:    sub sp, sp, #0xd0
; ARM64:    stp x29, x30, [sp]
; ARM64:    mov x29, sp
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    bl 0x2d0 <fcmp_f128_olt+0x30>
; ARM64:     R_AARCH64_CALL26 __lttf2
; ARM64:    cmp x0, #0x0
; ARM64:    cset w0, lt
; ARM64:    ldp x29, x30, [sp]
; ARM64:    add sp, sp, #0xd0
; ARM64:    ret
; ARM64:     ...
  %cmp = fcmp olt fp128 %0, %1
  ret i1 %cmp
}

define i1 @fcmp_f128_ole(fp128 %0, fp128 %1) {
; X64-LABEL: fcmp_f128_ole>:
; X64:    push rbp
; X64:    mov rbp, rsp
; X64:    nop word ptr [rax + rax]
; X64:    sub rsp, 0x60
; X64:  <L0>:
; X64:    call <L0>
; X64:     R_X86_64_PLT32 __letf2-0x4
; X64:    test rax, rax
; X64:    setle al
; X64:    movzx eax, al
; X64:    add rsp, 0x60
; X64:    pop rbp
; X64:    ret
; X64:     ...
;
; ARM64-LABEL: fcmp_f128_ole>:
; ARM64:    sub sp, sp, #0xd0
; ARM64:    stp x29, x30, [sp]
; ARM64:    mov x29, sp
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    bl 0x340 <fcmp_f128_ole+0x30>
; ARM64:     R_AARCH64_CALL26 __letf2
; ARM64:    cmp x0, #0x0
; ARM64:    cset w0, le
; ARM64:    ldp x29, x30, [sp]
; ARM64:    add sp, sp, #0xd0
; ARM64:    ret
; ARM64:     ...
  %cmp = fcmp ole fp128 %0, %1
  ret i1 %cmp
}

define i1 @fcmp_f128_uno(fp128 %0, fp128 %1) {
; X64-LABEL: fcmp_f128_uno>:
; X64:    push rbp
; X64:    mov rbp, rsp
; X64:    nop word ptr [rax + rax]
; X64:    sub rsp, 0x60
; X64:  <L0>:
; X64:    call <L0>
; X64:     R_X86_64_PLT32 __unordtf2-0x4
; X64:    test rax, rax
; X64:    setne al
; X64:    movzx eax, al
; X64:    add rsp, 0x60
; X64:    pop rbp
; X64:    ret
; X64:     ...
;
; ARM64-LABEL: fcmp_f128_uno>:
; ARM64:    sub sp, sp, #0xd0
; ARM64:    stp x29, x30, [sp]
; ARM64:    mov x29, sp
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    bl 0x3b0 <fcmp_f128_uno+0x30>
; ARM64:     R_AARCH64_CALL26 __unordtf2
; ARM64:    cmp x0, #0x0
; ARM64:    cset w0, ne
; ARM64:    ldp x29, x30, [sp]
; ARM64:    add sp, sp, #0xd0
; ARM64:    ret
; ARM64:     ...
  %cmp = fcmp uno fp128 %0, %1
  ret i1 %cmp
}

define i1 @fcmp_f128_ugt(fp128 %0, fp128 %1) {
; X64-LABEL: fcmp_f128_ugt>:
; X64:    push rbp
; X64:    mov rbp, rsp
; X64:    nop word ptr [rax + rax]
; X64:    sub rsp, 0x60
; X64:  <L0>:
; X64:    call <L0>
; X64:     R_X86_64_PLT32 __letf2-0x4
; X64:    test rax, rax
; X64:    setg al
; X64:    movzx eax, al
; X64:    add rsp, 0x60
; X64:    pop rbp
; X64:    ret
; X64:     ...
;
; ARM64-LABEL: fcmp_f128_ugt>:
; ARM64:    sub sp, sp, #0xd0
; ARM64:    stp x29, x30, [sp]
; ARM64:    mov x29, sp
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    bl 0x420 <fcmp_f128_ugt+0x30>
; ARM64:     R_AARCH64_CALL26 __letf2
; ARM64:    cmp x0, #0x0
; ARM64:    cset w0, gt
; ARM64:    ldp x29, x30, [sp]
; ARM64:    add sp, sp, #0xd0
; ARM64:    ret
; ARM64:     ...
  %cmp = fcmp ugt fp128 %0, %1
  ret i1 %cmp
}

define i1 @fcmp_f128_uge(fp128 %0, fp128 %1) {
; X64-LABEL: fcmp_f128_uge>:
; X64:    push rbp
; X64:    mov rbp, rsp
; X64:    nop word ptr [rax + rax]
; X64:    sub rsp, 0x60
; X64:  <L0>:
; X64:    call <L0>
; X64:     R_X86_64_PLT32 __lttf2-0x4
; X64:    test rax, rax
; X64:    setge al
; X64:    movzx eax, al
; X64:    add rsp, 0x60
; X64:    pop rbp
; X64:    ret
; X64:     ...
;
; ARM64-LABEL: fcmp_f128_uge>:
; ARM64:    sub sp, sp, #0xd0
; ARM64:    stp x29, x30, [sp]
; ARM64:    mov x29, sp
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    bl 0x490 <fcmp_f128_uge+0x30>
; ARM64:     R_AARCH64_CALL26 __lttf2
; ARM64:    cmp x0, #0x0
; ARM64:    cset w0, ge
; ARM64:    ldp x29, x30, [sp]
; ARM64:    add sp, sp, #0xd0
; ARM64:    ret
; ARM64:     ...
  %cmp = fcmp uge fp128 %0, %1
  ret i1 %cmp
}

define i1 @fcmp_f128_ult(fp128 %0, fp128 %1) {
; X64-LABEL: fcmp_f128_ult>:
; X64:    push rbp
; X64:    mov rbp, rsp
; X64:    nop word ptr [rax + rax]
; X64:    sub rsp, 0x60
; X64:  <L0>:
; X64:    call <L0>
; X64:     R_X86_64_PLT32 __getf2-0x4
; X64:    test rax, rax
; X64:    setl al
; X64:    movzx eax, al
; X64:    add rsp, 0x60
; X64:    pop rbp
; X64:    ret
; X64:     ...
;
; ARM64-LABEL: fcmp_f128_ult>:
; ARM64:    sub sp, sp, #0xd0
; ARM64:    stp x29, x30, [sp]
; ARM64:    mov x29, sp
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    bl 0x500 <fcmp_f128_ult+0x30>
; ARM64:     R_AARCH64_CALL26 __getf2
; ARM64:    cmp x0, #0x0
; ARM64:    cset w0, lt
; ARM64:    ldp x29, x30, [sp]
; ARM64:    add sp, sp, #0xd0
; ARM64:    ret
; ARM64:     ...
  %cmp = fcmp ult fp128 %0, %1
  ret i1 %cmp
}

define i1 @fcmp_f128_ule(fp128 %0, fp128 %1) {
; X64-LABEL: fcmp_f128_ule>:
; X64:    push rbp
; X64:    mov rbp, rsp
; X64:    nop word ptr [rax + rax]
; X64:    sub rsp, 0x60
; X64:  <L0>:
; X64:    call <L0>
; X64:     R_X86_64_PLT32 __gttf2-0x4
; X64:    test rax, rax
; X64:    setle al
; X64:    movzx eax, al
; X64:    add rsp, 0x60
; X64:    pop rbp
; X64:    ret
; X64:     ...
;
; ARM64-LABEL: fcmp_f128_ule>:
; ARM64:    sub sp, sp, #0xd0
; ARM64:    stp x29, x30, [sp]
; ARM64:    mov x29, sp
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    bl 0x570 <fcmp_f128_ule+0x30>
; ARM64:     R_AARCH64_CALL26 __gttf2
; ARM64:    cmp x0, #0x0
; ARM64:    cset w0, le
; ARM64:    ldp x29, x30, [sp]
; ARM64:    add sp, sp, #0xd0
; ARM64:    ret
; ARM64:     ...
  %cmp = fcmp ule fp128 %0, %1
  ret i1 %cmp
}

define i1 @fcmp_f128_une(fp128 %0, fp128 %1) {
; X64-LABEL: fcmp_f128_une>:
; X64:    push rbp
; X64:    mov rbp, rsp
; X64:    nop word ptr [rax + rax]
; X64:    sub rsp, 0x60
; X64:  <L0>:
; X64:    call <L0>
; X64:     R_X86_64_PLT32 __netf2-0x4
; X64:    test rax, rax
; X64:    setne al
; X64:    movzx eax, al
; X64:    add rsp, 0x60
; X64:    pop rbp
; X64:    ret
; X64:     ...
;
; ARM64-LABEL: fcmp_f128_une>:
; ARM64:    sub sp, sp, #0xd0
; ARM64:    stp x29, x30, [sp]
; ARM64:    mov x29, sp
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    nop
; ARM64:    bl 0x5e0 <fcmp_f128_une+0x30>
; ARM64:     R_AARCH64_CALL26 __netf2
; ARM64:    cmp x0, #0x0
; ARM64:    cset w0, ne
; ARM64:    ldp x29, x30, [sp]
; ARM64:    add sp, sp, #0xd0
; ARM64:    ret
; ARM64:     ...
  %cmp = fcmp une fp128 %0, %1
  ret i1 %cmp
}

; define i1 @fcmp_f128_one(fp128 %0, fp128 %1) {
;   %cmp = fcmp one fp128 %0, %1
;   ret i1 %cmp
; }

; define i1 @fcmp_f128_ueq(fp128 %0, fp128 %1) {
;   %cmp = fcmp ueq fp128 %0, %1
;   ret i1 %cmp
; }

; define i1 @fcmp_f128_one_nonan(fp128 %0, fp128 %1) {
;   %cmp = fcmp nnan one fp128 %0, %1
;   ret i1 %cmp
; }

; define i1 @fcmp_f128_oeq_0(fp128 %0) {
;   %cmp = fcmp oeq fp128 %0, 0xL00000000000000000000000000000000
;   ret i1 %cmp
; }
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
